# This is a basic workflow to help you get started with Actions

name: github-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [  ]
  pull_request:
    branches: [ ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      
      # Runs a set of commands using the runners shell
      - name: Install Haxe Libraries
        run: |
            haxelib setup ~/haxelib
            haxelib install hxcpp
            haxelib install lime
            haxelib install openfl
            haxelib --never install flixel
            haxelib run lime setup flixel
            haxelib run lime setup
            haxelib install flixel-tools
            haxelib install flixel-ui
            haxelib install flixel-addons
            haxelib git linc_luajit https://github.com/Leather128/linc_luajit.git
            haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved
            haxelib git scriptless-polymod https://github.com/swordcube/scriptless-polymod
            haxelib install hxvlc
            haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
            haxelib git fnf-modcharting-tools https://github.com/Vortex2Oblivion/FNF-Modcharting-Tools
            haxelib git flxanimate https://github.com/Vortex2Oblivion/flxanimate
            haxelib git hxNoise https://github.com/whuop/hxNoise
            haxelib git funkin.vis https://github.com/FNF-CNE-Devs/funkVis grig-test
            haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio
            haxelib install hxcpp-debug-server
            haxelib git dox https://github.com/HaxeFoundation/dox
            haxelib install format
            haxelib install tjson
            haxelib list
      
      - name: Create Documentation Site
        run: |
            chmod +x docs/docs.sh
            docs/docs.sh
      
      - name: github-actions deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages # The folder the action should deploy.